#configuration.yaml
application:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "zero2prod@zbra.club"
  authorization_token: "3dc6eaaa-a239-4852-a6d5-36578f32cf91"
  timeout_milliseconds: 10000
